export const SET_DEPARTAMENTOS = 'SET_DEPARTAMENTOS'

export const SET_DEPARTAMENTOS_LIST = 'SET_DEPARTAMENTOS_LIST'

export const SET_DISCIPLINA = 'SET_DISCIPLINA'

export const SET_DISCIPLINAS_LIST = 'SET_DISCIPLINAS_LIST'

export const SET_CADASTRA_DISCIPLINA = 'SET_CADASTRA_DISCIPLINA'

export const SET_DISCIPLINA_ATUALIZADA = 'SET_DISCIPLINA_ATUALIZADA'

export const SET_DISCIPLINA_REMOVIDA = 'SET_DISCIPLINA_REMOVIDA'

export const SET_CURSOS_LIST = 'SET_CURSOS_LIST'

export const SET_SIDE_MENU = 'SET_SIDE_MENU'

export const SET_DOCENTES = 'SET_DOCENTES'

export const SET_AUTH_USER = 'SET_AUTH_USER'

export const SET_DOCENTE = 'SET_DOCENTE'

export const SET_CADASTRA_USUARIO = 'SET_CADASTRA_USUARIO'

export const SET_AREA_CONHECIMENTO_LIST = 'SET_AREA_CONHECIMENTO_LIST'

export const SET_USUARIO_LOGADO = 'SET_USUARIO_LOGADO'

export const SET_USUARIO_BOOLEN_LOGADO = 'SET_USUARIO_BOOLEN_LOGADO'

export const SET_MODALIDADE_BOLSA = 'SET_MODALIDADE_BOLSA'

export const SET_PERMISSAO_USUARIO = 'SET_PERMISSAO_USUARIO'

export const SET_ALUNO = 'SET_ALUNO'

export const SET_ALUNOS_LIST = 'SET_ALUNOS_LIST'

export const SET_ALUNO_FILTRO = 'SET_ALUNO_FILTRO'

export const SET_CADASTRA_ALUNO = 'SET_CADASTRA_ALUNO'

export const SET_ALUNO_ATUALIZADO = 'SET_ALUNO_ATUALIZADO'

export const SET_ALUNO_REMOVIDO = 'SET_ALUNO_REMOVIDO'

export const SET_PROJETOS_PESQUISA_LIST = 'SET_PROJETOS_PESQUISA_LIST'

export const SET_PROJETO_PESQUISA = 'SET_PROJETO_PESQUISA'

export const SET_CADASTRA_PROJETO_PESQUISA = 'SET_CADASTRA_PROJETO_PESQUISA'

export const SET_PROJETO_PESQUISA_ATUALIZADO = 'SET_PROJETO_PESQUISA_ATUALIZADO'

export const SET_PROJETO_PESQUISA_REMOVIDO = 'SET_PROJETO_PESQUISA_REMOVIDO'
