export const SET_DEPARTAMENTOS = 'SET_DEPARTAMENTOS'

export const SET_SIDE_MENU = 'SET_SIDE_MENU'

export const SET_AUTH_USER = 'SET_AUTH_USER'

export const SET_ALL_USERS = 'SET_ALL_USERS'

export const SET_DOCENTES = 'SET_DOCENTES'

export const SET_DEPARTAMENTOS_SELECT = 'SET_DEPARTAMENTOS_SELECT'

export const SET_DOCENTE = 'SET_DOCENTE'
